/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as EmbedRouteRouteImport } from './routes/embed/route'
import { Route as PRouteRouteImport } from './routes/p/route'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as Site404RouteImport } from './routes/_site/404'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteAgentIaRouteImport } from './routes/_site/agent-ia'
import { Route as SiteCaseStudiesRouteImport } from './routes/_site/case-studies'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteInsightsRouteImport } from './routes/_site/insights'
import { Route as SitePortfolioRouteImport } from './routes/_site/portfolio'
import { Route as SiteServicesRouteImport } from './routes/_site/services'
import { Route as SiteTarifsRouteImport } from './routes/_site/tarifs'
import { Route as AppEspaceRouteRouteImport } from './routes/app/_espace/route'
import { Route as AppConfirmerRouteImport } from './routes/app/confirmer'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppReinitialiserRouteImport } from './routes/app/reinitialiser'
import { Route as EmbedSlugRouteImport } from './routes/embed/$slug'
import { Route as EnEmbedRouteRouteImport } from './routes/en/embed/route'
import { Route as EnPRouteRouteImport } from './routes/en/p/route'
import { Route as PSlugRouteImport } from './routes/p/$slug'
import { Route as SiteEnIndexRouteImport } from './routes/_site/en/index'
import { Route as SiteEn404RouteImport } from './routes/_site/en/404'
import { Route as SiteEnAboutRouteImport } from './routes/_site/en/about'
import { Route as SiteEnAiAgentRouteImport } from './routes/_site/en/ai-agent'
import { Route as SiteEnCaseStudiesRouteImport } from './routes/_site/en/case-studies'
import { Route as SiteEnContactRouteImport } from './routes/_site/en/contact'
import { Route as SiteEnInsightsRouteImport } from './routes/_site/en/insights'
import { Route as SiteEnPortfolioRouteImport } from './routes/_site/en/portfolio'
import { Route as SiteEnPricingRouteImport } from './routes/_site/en/pricing'
import { Route as SiteEnServicesRouteImport } from './routes/_site/en/services'
import { Route as AppEspaceIndexRouteImport } from './routes/app/_espace/index'
import { Route as AppEspaceOrganisationRouteImport } from './routes/app/_espace/organisation'
import { Route as EmbedVisiteSlugRouteImport } from './routes/embed/visite/$slug'
import { Route as EnEmbedSlugRouteImport } from './routes/en/embed/$slug'
import { Route as EnPSlugRouteImport } from './routes/en/p/$slug'
import { Route as PSlugDonneesPersonnellesRouteImport } from './routes/p/$slug/donnees-personnelles'
import { Route as AppEspaceProjetsIdRouteRouteImport } from './routes/app/_espace/projets/$id/route'
import { Route as EnEmbedTourSlugRouteImport } from './routes/en/embed/tour/$slug'
import { Route as EnPSlugPrivacyRouteImport } from './routes/en/p/$slug/privacy'
import { Route as PSlugLotNumeroRouteImport } from './routes/p/$slug/lot/$numero'
import { Route as AppEspaceProjetsIdIndexRouteImport } from './routes/app/_espace/projets/$id/index'
import { Route as AppEspaceProjetsIdAnglaisRouteImport } from './routes/app/_espace/projets/$id/anglais'
import { Route as AppEspaceProjetsIdApercuRouteImport } from './routes/app/_espace/projets/$id/apercu'
import { Route as AppEspaceProjetsIdDemandesRouteImport } from './routes/app/_espace/projets/$id/demandes'
import { Route as AppEspaceProjetsIdLotsRouteImport } from './routes/app/_espace/projets/$id/lots'
import { Route as AppEspaceProjetsIdMarqueRouteImport } from './routes/app/_espace/projets/$id/marque'
import { Route as AppEspaceProjetsIdMediasRouteImport } from './routes/app/_espace/projets/$id/medias'
import { Route as AppEspaceProjetsIdPartageRouteImport } from './routes/app/_espace/projets/$id/partage'
import { Route as AppEspaceProjetsIdPlanRouteImport } from './routes/app/_espace/projets/$id/plan'
import { Route as AppEspaceProjetsIdReglagesRouteImport } from './routes/app/_espace/projets/$id/reglages'
import { Route as AppEspaceProjetsIdStatistiquesRouteImport } from './routes/app/_espace/projets/$id/statistiques'
import { Route as AppEspaceProjetsIdTypologiesRouteImport } from './routes/app/_espace/projets/$id/typologies'
import { Route as AppEspaceProjetsIdVisiteRouteImport } from './routes/app/_espace/projets/$id/visite'
import { Route as EnPSlugLotNumeroRouteImport } from './routes/en/p/$slug/lot/$numero'

const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRouteRoute = EmbedRouteRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const PRouteRoute = PRouteRouteImport.update({
  id: '/p',
  path: '/p',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const Site404Route = Site404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteAgentIaRoute = SiteAgentIaRouteImport.update({
  id: '/agent-ia',
  path: '/agent-ia',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteCaseStudiesRoute = SiteCaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteInsightsRoute = SiteInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SitePortfolioRoute = SitePortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteTarifsRoute = SiteTarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => SiteRouteRoute,
} as any)
const AppEspaceRouteRoute = AppEspaceRouteRouteImport.update({
  id: '/_espace',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfirmerRoute = AppConfirmerRouteImport.update({
  id: '/confirmer',
  path: '/confirmer',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReinitialiserRoute = AppReinitialiserRouteImport.update({
  id: '/reinitialiser',
  path: '/reinitialiser',
  getParentRoute: () => AppRouteRoute,
} as any)
const EmbedSlugRoute = EmbedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EmbedRouteRoute,
} as any)
const EnEmbedRouteRoute = EnEmbedRouteRouteImport.update({
  id: '/en/embed',
  path: '/en/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPRouteRoute = EnPRouteRouteImport.update({
  id: '/en/p',
  path: '/en/p',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PRouteRoute,
} as any)
const SiteEnIndexRoute = SiteEnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteEn404Route = SiteEn404RouteImport.update({
  id: '/en/404',
  path: '/en/404',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteEnAboutRoute = SiteEnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteEnAiAgentRoute = SiteEnAiAgentRouteImport.update({
  id: '/en/ai-agent',
  path: '/en/ai-agent',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteEnCaseStudiesRoute = SiteEnCaseStudiesRouteImport.update({
  id: '/en/case-studies',
  path: '/en/case-studies',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteEnContactRoute = SiteEnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteEnInsightsRoute = SiteEnInsightsRouteImport.update({
  id: '/en/insights',
  path: '/en/insights',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteEnPortfolioRoute = SiteEnPortfolioRouteImport.update({
  id: '/en/portfolio',
  path: '/en/portfolio',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteEnPricingRoute = SiteEnPricingRouteImport.update({
  id: '/en/pricing',
  path: '/en/pricing',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteEnServicesRoute = SiteEnServicesRouteImport.update({
  id: '/en/services',
  path: '/en/services',
  getParentRoute: () => SiteRouteRoute,
} as any)
const AppEspaceIndexRoute = AppEspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEspaceRouteRoute,
} as any)
const AppEspaceOrganisationRoute = AppEspaceOrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => AppEspaceRouteRoute,
} as any)
const EmbedVisiteSlugRoute = EmbedVisiteSlugRouteImport.update({
  id: '/visite/$slug',
  path: '/visite/$slug',
  getParentRoute: () => EmbedRouteRoute,
} as any)
const EnEmbedSlugRoute = EnEmbedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnEmbedRouteRoute,
} as any)
const EnPSlugRoute = EnPSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnPRouteRoute,
} as any)
const PSlugDonneesPersonnellesRoute =
  PSlugDonneesPersonnellesRouteImport.update({
    id: '/donnees-personnelles',
    path: '/donnees-personnelles',
    getParentRoute: () => PSlugRoute,
  } as any)
const AppEspaceProjetsIdRouteRoute = AppEspaceProjetsIdRouteRouteImport.update({
  id: '/projets/$id',
  path: '/projets/$id',
  getParentRoute: () => AppEspaceRouteRoute,
} as any)
const EnEmbedTourSlugRoute = EnEmbedTourSlugRouteImport.update({
  id: '/tour/$slug',
  path: '/tour/$slug',
  getParentRoute: () => EnEmbedRouteRoute,
} as any)
const EnPSlugPrivacyRoute = EnPSlugPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => EnPSlugRoute,
} as any)
const PSlugLotNumeroRoute = PSlugLotNumeroRouteImport.update({
  id: '/lot/$numero',
  path: '/lot/$numero',
  getParentRoute: () => PSlugRoute,
} as any)
const AppEspaceProjetsIdIndexRoute = AppEspaceProjetsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEspaceProjetsIdRouteRoute,
} as any)
const AppEspaceProjetsIdAnglaisRoute =
  AppEspaceProjetsIdAnglaisRouteImport.update({
    id: '/anglais',
    path: '/anglais',
    getParentRoute: () => AppEspaceProjetsIdRouteRoute,
  } as any)
const AppEspaceProjetsIdApercuRoute =
  AppEspaceProjetsIdApercuRouteImport.update({
    id: '/apercu',
    path: '/apercu',
    getParentRoute: () => AppEspaceProjetsIdRouteRoute,
  } as any)
const AppEspaceProjetsIdDemandesRoute =
  AppEspaceProjetsIdDemandesRouteImport.update({
    id: '/demandes',
    path: '/demandes',
    getParentRoute: () => AppEspaceProjetsIdRouteRoute,
  } as any)
const AppEspaceProjetsIdLotsRoute = AppEspaceProjetsIdLotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => AppEspaceProjetsIdRouteRoute,
} as any)
const AppEspaceProjetsIdMarqueRoute =
  AppEspaceProjetsIdMarqueRouteImport.update({
    id: '/marque',
    path: '/marque',
    getParentRoute: () => AppEspaceProjetsIdRouteRoute,
  } as any)
const AppEspaceProjetsIdMediasRoute =
  AppEspaceProjetsIdMediasRouteImport.update({
    id: '/medias',
    path: '/medias',
    getParentRoute: () => AppEspaceProjetsIdRouteRoute,
  } as any)
const AppEspaceProjetsIdPartageRoute =
  AppEspaceProjetsIdPartageRouteImport.update({
    id: '/partage',
    path: '/partage',
    getParentRoute: () => AppEspaceProjetsIdRouteRoute,
  } as any)
const AppEspaceProjetsIdPlanRoute = AppEspaceProjetsIdPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppEspaceProjetsIdRouteRoute,
} as any)
const AppEspaceProjetsIdReglagesRoute =
  AppEspaceProjetsIdReglagesRouteImport.update({
    id: '/reglages',
    path: '/reglages',
    getParentRoute: () => AppEspaceProjetsIdRouteRoute,
  } as any)
const AppEspaceProjetsIdStatistiquesRoute =
  AppEspaceProjetsIdStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => AppEspaceProjetsIdRouteRoute,
  } as any)
const AppEspaceProjetsIdTypologiesRoute =
  AppEspaceProjetsIdTypologiesRouteImport.update({
    id: '/typologies',
    path: '/typologies',
    getParentRoute: () => AppEspaceProjetsIdRouteRoute,
  } as any)
const AppEspaceProjetsIdVisiteRoute =
  AppEspaceProjetsIdVisiteRouteImport.update({
    id: '/visite',
    path: '/visite',
    getParentRoute: () => AppEspaceProjetsIdRouteRoute,
  } as any)
const EnPSlugLotNumeroRoute = EnPSlugLotNumeroRouteImport.update({
  id: '/lot/$numero',
  path: '/lot/$numero',
  getParentRoute: () => EnPSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/embed': typeof EmbedRouteRouteWithChildren
  '/p': typeof PRouteRouteWithChildren
  '/en/embed': typeof EnEmbedRouteRouteWithChildren
  '/en/p': typeof EnPRouteRouteWithChildren
  '/404': typeof Site404Route
  '/about': typeof SiteAboutRoute
  '/agent-ia': typeof SiteAgentIaRoute
  '/case-studies': typeof SiteCaseStudiesRoute
  '/contact': typeof SiteContactRoute
  '/insights': typeof SiteInsightsRoute
  '/portfolio': typeof SitePortfolioRoute
  '/services': typeof SiteServicesRoute
  '/tarifs': typeof SiteTarifsRoute
  '/app/confirmer': typeof AppConfirmerRoute
  '/app/login': typeof AppLoginRoute
  '/app/reinitialiser': typeof AppReinitialiserRoute
  '/embed/$slug': typeof EmbedSlugRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/en/404': typeof SiteEn404Route
  '/en/about': typeof SiteEnAboutRoute
  '/en/ai-agent': typeof SiteEnAiAgentRoute
  '/en/case-studies': typeof SiteEnCaseStudiesRoute
  '/en/contact': typeof SiteEnContactRoute
  '/en/insights': typeof SiteEnInsightsRoute
  '/en/portfolio': typeof SiteEnPortfolioRoute
  '/en/pricing': typeof SiteEnPricingRoute
  '/en/services': typeof SiteEnServicesRoute
  '/app/organisation': typeof AppEspaceOrganisationRoute
  '/embed/visite/$slug': typeof EmbedVisiteSlugRoute
  '/en/embed/$slug': typeof EnEmbedSlugRoute
  '/en/p/$slug': typeof EnPSlugRouteWithChildren
  '/p/$slug/donnees-personnelles': typeof PSlugDonneesPersonnellesRoute
  '/en/': typeof SiteEnIndexRoute
  '/app/': typeof AppEspaceIndexRoute
  '/app/projets/$id': typeof AppEspaceProjetsIdRouteRouteWithChildren
  '/en/embed/tour/$slug': typeof EnEmbedTourSlugRoute
  '/en/p/$slug/privacy': typeof EnPSlugPrivacyRoute
  '/p/$slug/lot/$numero': typeof PSlugLotNumeroRoute
  '/app/projets/$id/anglais': typeof AppEspaceProjetsIdAnglaisRoute
  '/app/projets/$id/apercu': typeof AppEspaceProjetsIdApercuRoute
  '/app/projets/$id/demandes': typeof AppEspaceProjetsIdDemandesRoute
  '/app/projets/$id/lots': typeof AppEspaceProjetsIdLotsRoute
  '/app/projets/$id/marque': typeof AppEspaceProjetsIdMarqueRoute
  '/app/projets/$id/medias': typeof AppEspaceProjetsIdMediasRoute
  '/app/projets/$id/partage': typeof AppEspaceProjetsIdPartageRoute
  '/app/projets/$id/plan': typeof AppEspaceProjetsIdPlanRoute
  '/app/projets/$id/reglages': typeof AppEspaceProjetsIdReglagesRoute
  '/app/projets/$id/statistiques': typeof AppEspaceProjetsIdStatistiquesRoute
  '/app/projets/$id/typologies': typeof AppEspaceProjetsIdTypologiesRoute
  '/app/projets/$id/visite': typeof AppEspaceProjetsIdVisiteRoute
  '/en/p/$slug/lot/$numero': typeof EnPSlugLotNumeroRoute
  '/app/projets/$id/': typeof AppEspaceProjetsIdIndexRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppEspaceIndexRoute
  '/embed': typeof EmbedRouteRouteWithChildren
  '/p': typeof PRouteRouteWithChildren
  '/en/embed': typeof EnEmbedRouteRouteWithChildren
  '/en/p': typeof EnPRouteRouteWithChildren
  '/404': typeof Site404Route
  '/about': typeof SiteAboutRoute
  '/agent-ia': typeof SiteAgentIaRoute
  '/case-studies': typeof SiteCaseStudiesRoute
  '/contact': typeof SiteContactRoute
  '/insights': typeof SiteInsightsRoute
  '/portfolio': typeof SitePortfolioRoute
  '/services': typeof SiteServicesRoute
  '/tarifs': typeof SiteTarifsRoute
  '/app/confirmer': typeof AppConfirmerRoute
  '/app/login': typeof AppLoginRoute
  '/app/reinitialiser': typeof AppReinitialiserRoute
  '/embed/$slug': typeof EmbedSlugRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/': typeof SiteIndexRoute
  '/en/404': typeof SiteEn404Route
  '/en/about': typeof SiteEnAboutRoute
  '/en/ai-agent': typeof SiteEnAiAgentRoute
  '/en/case-studies': typeof SiteEnCaseStudiesRoute
  '/en/contact': typeof SiteEnContactRoute
  '/en/insights': typeof SiteEnInsightsRoute
  '/en/portfolio': typeof SiteEnPortfolioRoute
  '/en/pricing': typeof SiteEnPricingRoute
  '/en/services': typeof SiteEnServicesRoute
  '/app/organisation': typeof AppEspaceOrganisationRoute
  '/embed/visite/$slug': typeof EmbedVisiteSlugRoute
  '/en/embed/$slug': typeof EnEmbedSlugRoute
  '/en/p/$slug': typeof EnPSlugRouteWithChildren
  '/p/$slug/donnees-personnelles': typeof PSlugDonneesPersonnellesRoute
  '/en': typeof SiteEnIndexRoute
  '/en/embed/tour/$slug': typeof EnEmbedTourSlugRoute
  '/en/p/$slug/privacy': typeof EnPSlugPrivacyRoute
  '/p/$slug/lot/$numero': typeof PSlugLotNumeroRoute
  '/app/projets/$id/anglais': typeof AppEspaceProjetsIdAnglaisRoute
  '/app/projets/$id/apercu': typeof AppEspaceProjetsIdApercuRoute
  '/app/projets/$id/demandes': typeof AppEspaceProjetsIdDemandesRoute
  '/app/projets/$id/lots': typeof AppEspaceProjetsIdLotsRoute
  '/app/projets/$id/marque': typeof AppEspaceProjetsIdMarqueRoute
  '/app/projets/$id/medias': typeof AppEspaceProjetsIdMediasRoute
  '/app/projets/$id/partage': typeof AppEspaceProjetsIdPartageRoute
  '/app/projets/$id/plan': typeof AppEspaceProjetsIdPlanRoute
  '/app/projets/$id/reglages': typeof AppEspaceProjetsIdReglagesRoute
  '/app/projets/$id/statistiques': typeof AppEspaceProjetsIdStatistiquesRoute
  '/app/projets/$id/typologies': typeof AppEspaceProjetsIdTypologiesRoute
  '/app/projets/$id/visite': typeof AppEspaceProjetsIdVisiteRoute
  '/en/p/$slug/lot/$numero': typeof EnPSlugLotNumeroRoute
  '/app/projets/$id': typeof AppEspaceProjetsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/embed': typeof EmbedRouteRouteWithChildren
  '/p': typeof PRouteRouteWithChildren
  '/app/_espace': typeof AppEspaceRouteRouteWithChildren
  '/en/embed': typeof EnEmbedRouteRouteWithChildren
  '/en/p': typeof EnPRouteRouteWithChildren
  '/_site/404': typeof Site404Route
  '/_site/about': typeof SiteAboutRoute
  '/_site/agent-ia': typeof SiteAgentIaRoute
  '/_site/case-studies': typeof SiteCaseStudiesRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/insights': typeof SiteInsightsRoute
  '/_site/portfolio': typeof SitePortfolioRoute
  '/_site/services': typeof SiteServicesRoute
  '/_site/tarifs': typeof SiteTarifsRoute
  '/app/confirmer': typeof AppConfirmerRoute
  '/app/login': typeof AppLoginRoute
  '/app/reinitialiser': typeof AppReinitialiserRoute
  '/embed/$slug': typeof EmbedSlugRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/_site/': typeof SiteIndexRoute
  '/_site/en/404': typeof SiteEn404Route
  '/_site/en/about': typeof SiteEnAboutRoute
  '/_site/en/ai-agent': typeof SiteEnAiAgentRoute
  '/_site/en/case-studies': typeof SiteEnCaseStudiesRoute
  '/_site/en/contact': typeof SiteEnContactRoute
  '/_site/en/insights': typeof SiteEnInsightsRoute
  '/_site/en/portfolio': typeof SiteEnPortfolioRoute
  '/_site/en/pricing': typeof SiteEnPricingRoute
  '/_site/en/services': typeof SiteEnServicesRoute
  '/app/_espace/organisation': typeof AppEspaceOrganisationRoute
  '/embed/visite/$slug': typeof EmbedVisiteSlugRoute
  '/en/embed/$slug': typeof EnEmbedSlugRoute
  '/en/p/$slug': typeof EnPSlugRouteWithChildren
  '/p/$slug/donnees-personnelles': typeof PSlugDonneesPersonnellesRoute
  '/_site/en/': typeof SiteEnIndexRoute
  '/app/_espace/': typeof AppEspaceIndexRoute
  '/app/_espace/projets/$id': typeof AppEspaceProjetsIdRouteRouteWithChildren
  '/en/embed/tour/$slug': typeof EnEmbedTourSlugRoute
  '/en/p/$slug/privacy': typeof EnPSlugPrivacyRoute
  '/p/$slug/lot/$numero': typeof PSlugLotNumeroRoute
  '/app/_espace/projets/$id/anglais': typeof AppEspaceProjetsIdAnglaisRoute
  '/app/_espace/projets/$id/apercu': typeof AppEspaceProjetsIdApercuRoute
  '/app/_espace/projets/$id/demandes': typeof AppEspaceProjetsIdDemandesRoute
  '/app/_espace/projets/$id/lots': typeof AppEspaceProjetsIdLotsRoute
  '/app/_espace/projets/$id/marque': typeof AppEspaceProjetsIdMarqueRoute
  '/app/_espace/projets/$id/medias': typeof AppEspaceProjetsIdMediasRoute
  '/app/_espace/projets/$id/partage': typeof AppEspaceProjetsIdPartageRoute
  '/app/_espace/projets/$id/plan': typeof AppEspaceProjetsIdPlanRoute
  '/app/_espace/projets/$id/reglages': typeof AppEspaceProjetsIdReglagesRoute
  '/app/_espace/projets/$id/statistiques': typeof AppEspaceProjetsIdStatistiquesRoute
  '/app/_espace/projets/$id/typologies': typeof AppEspaceProjetsIdTypologiesRoute
  '/app/_espace/projets/$id/visite': typeof AppEspaceProjetsIdVisiteRoute
  '/en/p/$slug/lot/$numero': typeof EnPSlugLotNumeroRoute
  '/app/_espace/projets/$id/': typeof AppEspaceProjetsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/embed'
    | '/p'
    | '/en/embed'
    | '/en/p'
    | '/404'
    | '/about'
    | '/agent-ia'
    | '/case-studies'
    | '/contact'
    | '/insights'
    | '/portfolio'
    | '/services'
    | '/tarifs'
    | '/app/confirmer'
    | '/app/login'
    | '/app/reinitialiser'
    | '/embed/$slug'
    | '/p/$slug'
    | '/en/404'
    | '/en/about'
    | '/en/ai-agent'
    | '/en/case-studies'
    | '/en/contact'
    | '/en/insights'
    | '/en/portfolio'
    | '/en/pricing'
    | '/en/services'
    | '/app/organisation'
    | '/embed/visite/$slug'
    | '/en/embed/$slug'
    | '/en/p/$slug'
    | '/p/$slug/donnees-personnelles'
    | '/en/'
    | '/app/'
    | '/app/projets/$id'
    | '/en/embed/tour/$slug'
    | '/en/p/$slug/privacy'
    | '/p/$slug/lot/$numero'
    | '/app/projets/$id/anglais'
    | '/app/projets/$id/apercu'
    | '/app/projets/$id/demandes'
    | '/app/projets/$id/lots'
    | '/app/projets/$id/marque'
    | '/app/projets/$id/medias'
    | '/app/projets/$id/partage'
    | '/app/projets/$id/plan'
    | '/app/projets/$id/reglages'
    | '/app/projets/$id/statistiques'
    | '/app/projets/$id/typologies'
    | '/app/projets/$id/visite'
    | '/en/p/$slug/lot/$numero'
    | '/app/projets/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/embed'
    | '/p'
    | '/en/embed'
    | '/en/p'
    | '/404'
    | '/about'
    | '/agent-ia'
    | '/case-studies'
    | '/contact'
    | '/insights'
    | '/portfolio'
    | '/services'
    | '/tarifs'
    | '/app/confirmer'
    | '/app/login'
    | '/app/reinitialiser'
    | '/embed/$slug'
    | '/p/$slug'
    | '/'
    | '/en/404'
    | '/en/about'
    | '/en/ai-agent'
    | '/en/case-studies'
    | '/en/contact'
    | '/en/insights'
    | '/en/portfolio'
    | '/en/pricing'
    | '/en/services'
    | '/app/organisation'
    | '/embed/visite/$slug'
    | '/en/embed/$slug'
    | '/en/p/$slug'
    | '/p/$slug/donnees-personnelles'
    | '/en'
    | '/en/embed/tour/$slug'
    | '/en/p/$slug/privacy'
    | '/p/$slug/lot/$numero'
    | '/app/projets/$id/anglais'
    | '/app/projets/$id/apercu'
    | '/app/projets/$id/demandes'
    | '/app/projets/$id/lots'
    | '/app/projets/$id/marque'
    | '/app/projets/$id/medias'
    | '/app/projets/$id/partage'
    | '/app/projets/$id/plan'
    | '/app/projets/$id/reglages'
    | '/app/projets/$id/statistiques'
    | '/app/projets/$id/typologies'
    | '/app/projets/$id/visite'
    | '/en/p/$slug/lot/$numero'
    | '/app/projets/$id'
  id:
    | '__root__'
    | '/_site'
    | '/app'
    | '/embed'
    | '/p'
    | '/app/_espace'
    | '/en/embed'
    | '/en/p'
    | '/_site/404'
    | '/_site/about'
    | '/_site/agent-ia'
    | '/_site/case-studies'
    | '/_site/contact'
    | '/_site/insights'
    | '/_site/portfolio'
    | '/_site/services'
    | '/_site/tarifs'
    | '/app/confirmer'
    | '/app/login'
    | '/app/reinitialiser'
    | '/embed/$slug'
    | '/p/$slug'
    | '/_site/'
    | '/_site/en/404'
    | '/_site/en/about'
    | '/_site/en/ai-agent'
    | '/_site/en/case-studies'
    | '/_site/en/contact'
    | '/_site/en/insights'
    | '/_site/en/portfolio'
    | '/_site/en/pricing'
    | '/_site/en/services'
    | '/app/_espace/organisation'
    | '/embed/visite/$slug'
    | '/en/embed/$slug'
    | '/en/p/$slug'
    | '/p/$slug/donnees-personnelles'
    | '/_site/en/'
    | '/app/_espace/'
    | '/app/_espace/projets/$id'
    | '/en/embed/tour/$slug'
    | '/en/p/$slug/privacy'
    | '/p/$slug/lot/$numero'
    | '/app/_espace/projets/$id/anglais'
    | '/app/_espace/projets/$id/apercu'
    | '/app/_espace/projets/$id/demandes'
    | '/app/_espace/projets/$id/lots'
    | '/app/_espace/projets/$id/marque'
    | '/app/_espace/projets/$id/medias'
    | '/app/_espace/projets/$id/partage'
    | '/app/_espace/projets/$id/plan'
    | '/app/_espace/projets/$id/reglages'
    | '/app/_espace/projets/$id/statistiques'
    | '/app/_espace/projets/$id/typologies'
    | '/app/_espace/projets/$id/visite'
    | '/en/p/$slug/lot/$numero'
    | '/app/_espace/projets/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  EmbedRouteRoute: typeof EmbedRouteRouteWithChildren
  PRouteRoute: typeof PRouteRouteWithChildren
  EnEmbedRouteRoute: typeof EnEmbedRouteRouteWithChildren
  EnPRouteRoute: typeof EnPRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p': {
      id: '/p'
      path: '/p'
      fullPath: '/p'
      preLoaderRoute: typeof PRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/404': {
      id: '/_site/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof Site404RouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/agent-ia': {
      id: '/_site/agent-ia'
      path: '/agent-ia'
      fullPath: '/agent-ia'
      preLoaderRoute: typeof SiteAgentIaRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/case-studies': {
      id: '/_site/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof SiteCaseStudiesRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/insights': {
      id: '/_site/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof SiteInsightsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/portfolio': {
      id: '/_site/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof SitePortfolioRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/tarifs': {
      id: '/_site/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof SiteTarifsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/app/_espace': {
      id: '/app/_espace'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppEspaceRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/confirmer': {
      id: '/app/confirmer'
      path: '/confirmer'
      fullPath: '/app/confirmer'
      preLoaderRoute: typeof AppConfirmerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reinitialiser': {
      id: '/app/reinitialiser'
      path: '/reinitialiser'
      fullPath: '/app/reinitialiser'
      preLoaderRoute: typeof AppReinitialiserRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/embed/$slug': {
      id: '/embed/$slug'
      path: '/$slug'
      fullPath: '/embed/$slug'
      preLoaderRoute: typeof EmbedSlugRouteImport
      parentRoute: typeof EmbedRouteRoute
    }
    '/en/embed': {
      id: '/en/embed'
      path: '/en/embed'
      fullPath: '/en/embed'
      preLoaderRoute: typeof EnEmbedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/p': {
      id: '/en/p'
      path: '/en/p'
      fullPath: '/en/p'
      preLoaderRoute: typeof EnPRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof PRouteRoute
    }
    '/_site/en/': {
      id: '/_site/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof SiteEnIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/en/404': {
      id: '/_site/en/404'
      path: '/en/404'
      fullPath: '/en/404'
      preLoaderRoute: typeof SiteEn404RouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/en/about': {
      id: '/_site/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof SiteEnAboutRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/en/ai-agent': {
      id: '/_site/en/ai-agent'
      path: '/en/ai-agent'
      fullPath: '/en/ai-agent'
      preLoaderRoute: typeof SiteEnAiAgentRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/en/case-studies': {
      id: '/_site/en/case-studies'
      path: '/en/case-studies'
      fullPath: '/en/case-studies'
      preLoaderRoute: typeof SiteEnCaseStudiesRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/en/contact': {
      id: '/_site/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof SiteEnContactRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/en/insights': {
      id: '/_site/en/insights'
      path: '/en/insights'
      fullPath: '/en/insights'
      preLoaderRoute: typeof SiteEnInsightsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/en/portfolio': {
      id: '/_site/en/portfolio'
      path: '/en/portfolio'
      fullPath: '/en/portfolio'
      preLoaderRoute: typeof SiteEnPortfolioRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/en/pricing': {
      id: '/_site/en/pricing'
      path: '/en/pricing'
      fullPath: '/en/pricing'
      preLoaderRoute: typeof SiteEnPricingRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/en/services': {
      id: '/_site/en/services'
      path: '/en/services'
      fullPath: '/en/services'
      preLoaderRoute: typeof SiteEnServicesRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/app/_espace/': {
      id: '/app/_espace/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppEspaceIndexRouteImport
      parentRoute: typeof AppEspaceRouteRoute
    }
    '/app/_espace/organisation': {
      id: '/app/_espace/organisation'
      path: '/organisation'
      fullPath: '/app/organisation'
      preLoaderRoute: typeof AppEspaceOrganisationRouteImport
      parentRoute: typeof AppEspaceRouteRoute
    }
    '/embed/visite/$slug': {
      id: '/embed/visite/$slug'
      path: '/visite/$slug'
      fullPath: '/embed/visite/$slug'
      preLoaderRoute: typeof EmbedVisiteSlugRouteImport
      parentRoute: typeof EmbedRouteRoute
    }
    '/en/embed/$slug': {
      id: '/en/embed/$slug'
      path: '/$slug'
      fullPath: '/en/embed/$slug'
      preLoaderRoute: typeof EnEmbedSlugRouteImport
      parentRoute: typeof EnEmbedRouteRoute
    }
    '/en/p/$slug': {
      id: '/en/p/$slug'
      path: '/$slug'
      fullPath: '/en/p/$slug'
      preLoaderRoute: typeof EnPSlugRouteImport
      parentRoute: typeof EnPRouteRoute
    }
    '/p/$slug/donnees-personnelles': {
      id: '/p/$slug/donnees-personnelles'
      path: '/donnees-personnelles'
      fullPath: '/p/$slug/donnees-personnelles'
      preLoaderRoute: typeof PSlugDonneesPersonnellesRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/app/_espace/projets/$id': {
      id: '/app/_espace/projets/$id'
      path: '/projets/$id'
      fullPath: '/app/projets/$id'
      preLoaderRoute: typeof AppEspaceProjetsIdRouteRouteImport
      parentRoute: typeof AppEspaceRouteRoute
    }
    '/en/embed/tour/$slug': {
      id: '/en/embed/tour/$slug'
      path: '/tour/$slug'
      fullPath: '/en/embed/tour/$slug'
      preLoaderRoute: typeof EnEmbedTourSlugRouteImport
      parentRoute: typeof EnEmbedRouteRoute
    }
    '/en/p/$slug/privacy': {
      id: '/en/p/$slug/privacy'
      path: '/privacy'
      fullPath: '/en/p/$slug/privacy'
      preLoaderRoute: typeof EnPSlugPrivacyRouteImport
      parentRoute: typeof EnPSlugRoute
    }
    '/p/$slug/lot/$numero': {
      id: '/p/$slug/lot/$numero'
      path: '/lot/$numero'
      fullPath: '/p/$slug/lot/$numero'
      preLoaderRoute: typeof PSlugLotNumeroRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/app/_espace/projets/$id/': {
      id: '/app/_espace/projets/$id/'
      path: '/'
      fullPath: '/app/projets/$id/'
      preLoaderRoute: typeof AppEspaceProjetsIdIndexRouteImport
      parentRoute: typeof AppEspaceProjetsIdRouteRoute
    }
    '/app/_espace/projets/$id/anglais': {
      id: '/app/_espace/projets/$id/anglais'
      path: '/anglais'
      fullPath: '/app/projets/$id/anglais'
      preLoaderRoute: typeof AppEspaceProjetsIdAnglaisRouteImport
      parentRoute: typeof AppEspaceProjetsIdRouteRoute
    }
    '/app/_espace/projets/$id/apercu': {
      id: '/app/_espace/projets/$id/apercu'
      path: '/apercu'
      fullPath: '/app/projets/$id/apercu'
      preLoaderRoute: typeof AppEspaceProjetsIdApercuRouteImport
      parentRoute: typeof AppEspaceProjetsIdRouteRoute
    }
    '/app/_espace/projets/$id/demandes': {
      id: '/app/_espace/projets/$id/demandes'
      path: '/demandes'
      fullPath: '/app/projets/$id/demandes'
      preLoaderRoute: typeof AppEspaceProjetsIdDemandesRouteImport
      parentRoute: typeof AppEspaceProjetsIdRouteRoute
    }
    '/app/_espace/projets/$id/lots': {
      id: '/app/_espace/projets/$id/lots'
      path: '/lots'
      fullPath: '/app/projets/$id/lots'
      preLoaderRoute: typeof AppEspaceProjetsIdLotsRouteImport
      parentRoute: typeof AppEspaceProjetsIdRouteRoute
    }
    '/app/_espace/projets/$id/marque': {
      id: '/app/_espace/projets/$id/marque'
      path: '/marque'
      fullPath: '/app/projets/$id/marque'
      preLoaderRoute: typeof AppEspaceProjetsIdMarqueRouteImport
      parentRoute: typeof AppEspaceProjetsIdRouteRoute
    }
    '/app/_espace/projets/$id/medias': {
      id: '/app/_espace/projets/$id/medias'
      path: '/medias'
      fullPath: '/app/projets/$id/medias'
      preLoaderRoute: typeof AppEspaceProjetsIdMediasRouteImport
      parentRoute: typeof AppEspaceProjetsIdRouteRoute
    }
    '/app/_espace/projets/$id/partage': {
      id: '/app/_espace/projets/$id/partage'
      path: '/partage'
      fullPath: '/app/projets/$id/partage'
      preLoaderRoute: typeof AppEspaceProjetsIdPartageRouteImport
      parentRoute: typeof AppEspaceProjetsIdRouteRoute
    }
    '/app/_espace/projets/$id/plan': {
      id: '/app/_espace/projets/$id/plan'
      path: '/plan'
      fullPath: '/app/projets/$id/plan'
      preLoaderRoute: typeof AppEspaceProjetsIdPlanRouteImport
      parentRoute: typeof AppEspaceProjetsIdRouteRoute
    }
    '/app/_espace/projets/$id/reglages': {
      id: '/app/_espace/projets/$id/reglages'
      path: '/reglages'
      fullPath: '/app/projets/$id/reglages'
      preLoaderRoute: typeof AppEspaceProjetsIdReglagesRouteImport
      parentRoute: typeof AppEspaceProjetsIdRouteRoute
    }
    '/app/_espace/projets/$id/statistiques': {
      id: '/app/_espace/projets/$id/statistiques'
      path: '/statistiques'
      fullPath: '/app/projets/$id/statistiques'
      preLoaderRoute: typeof AppEspaceProjetsIdStatistiquesRouteImport
      parentRoute: typeof AppEspaceProjetsIdRouteRoute
    }
    '/app/_espace/projets/$id/typologies': {
      id: '/app/_espace/projets/$id/typologies'
      path: '/typologies'
      fullPath: '/app/projets/$id/typologies'
      preLoaderRoute: typeof AppEspaceProjetsIdTypologiesRouteImport
      parentRoute: typeof AppEspaceProjetsIdRouteRoute
    }
    '/app/_espace/projets/$id/visite': {
      id: '/app/_espace/projets/$id/visite'
      path: '/visite'
      fullPath: '/app/projets/$id/visite'
      preLoaderRoute: typeof AppEspaceProjetsIdVisiteRouteImport
      parentRoute: typeof AppEspaceProjetsIdRouteRoute
    }
    '/en/p/$slug/lot/$numero': {
      id: '/en/p/$slug/lot/$numero'
      path: '/lot/$numero'
      fullPath: '/en/p/$slug/lot/$numero'
      preLoaderRoute: typeof EnPSlugLotNumeroRouteImport
      parentRoute: typeof EnPSlugRoute
    }
  }
}

interface SiteRouteRouteChildren {
  Site404Route: typeof Site404Route
  SiteAboutRoute: typeof SiteAboutRoute
  SiteAgentIaRoute: typeof SiteAgentIaRoute
  SiteCaseStudiesRoute: typeof SiteCaseStudiesRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteInsightsRoute: typeof SiteInsightsRoute
  SitePortfolioRoute: typeof SitePortfolioRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteTarifsRoute: typeof SiteTarifsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteEn404Route: typeof SiteEn404Route
  SiteEnAboutRoute: typeof SiteEnAboutRoute
  SiteEnAiAgentRoute: typeof SiteEnAiAgentRoute
  SiteEnCaseStudiesRoute: typeof SiteEnCaseStudiesRoute
  SiteEnContactRoute: typeof SiteEnContactRoute
  SiteEnInsightsRoute: typeof SiteEnInsightsRoute
  SiteEnPortfolioRoute: typeof SiteEnPortfolioRoute
  SiteEnPricingRoute: typeof SiteEnPricingRoute
  SiteEnServicesRoute: typeof SiteEnServicesRoute
  SiteEnIndexRoute: typeof SiteEnIndexRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  Site404Route: Site404Route,
  SiteAboutRoute: SiteAboutRoute,
  SiteAgentIaRoute: SiteAgentIaRoute,
  SiteCaseStudiesRoute: SiteCaseStudiesRoute,
  SiteContactRoute: SiteContactRoute,
  SiteInsightsRoute: SiteInsightsRoute,
  SitePortfolioRoute: SitePortfolioRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteTarifsRoute: SiteTarifsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteEn404Route: SiteEn404Route,
  SiteEnAboutRoute: SiteEnAboutRoute,
  SiteEnAiAgentRoute: SiteEnAiAgentRoute,
  SiteEnCaseStudiesRoute: SiteEnCaseStudiesRoute,
  SiteEnContactRoute: SiteEnContactRoute,
  SiteEnInsightsRoute: SiteEnInsightsRoute,
  SiteEnPortfolioRoute: SiteEnPortfolioRoute,
  SiteEnPricingRoute: SiteEnPricingRoute,
  SiteEnServicesRoute: SiteEnServicesRoute,
  SiteEnIndexRoute: SiteEnIndexRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

interface AppEspaceProjetsIdRouteRouteChildren {
  AppEspaceProjetsIdAnglaisRoute: typeof AppEspaceProjetsIdAnglaisRoute
  AppEspaceProjetsIdApercuRoute: typeof AppEspaceProjetsIdApercuRoute
  AppEspaceProjetsIdDemandesRoute: typeof AppEspaceProjetsIdDemandesRoute
  AppEspaceProjetsIdLotsRoute: typeof AppEspaceProjetsIdLotsRoute
  AppEspaceProjetsIdMarqueRoute: typeof AppEspaceProjetsIdMarqueRoute
  AppEspaceProjetsIdMediasRoute: typeof AppEspaceProjetsIdMediasRoute
  AppEspaceProjetsIdPartageRoute: typeof AppEspaceProjetsIdPartageRoute
  AppEspaceProjetsIdPlanRoute: typeof AppEspaceProjetsIdPlanRoute
  AppEspaceProjetsIdReglagesRoute: typeof AppEspaceProjetsIdReglagesRoute
  AppEspaceProjetsIdStatistiquesRoute: typeof AppEspaceProjetsIdStatistiquesRoute
  AppEspaceProjetsIdTypologiesRoute: typeof AppEspaceProjetsIdTypologiesRoute
  AppEspaceProjetsIdVisiteRoute: typeof AppEspaceProjetsIdVisiteRoute
  AppEspaceProjetsIdIndexRoute: typeof AppEspaceProjetsIdIndexRoute
}

const AppEspaceProjetsIdRouteRouteChildren: AppEspaceProjetsIdRouteRouteChildren =
  {
    AppEspaceProjetsIdAnglaisRoute: AppEspaceProjetsIdAnglaisRoute,
    AppEspaceProjetsIdApercuRoute: AppEspaceProjetsIdApercuRoute,
    AppEspaceProjetsIdDemandesRoute: AppEspaceProjetsIdDemandesRoute,
    AppEspaceProjetsIdLotsRoute: AppEspaceProjetsIdLotsRoute,
    AppEspaceProjetsIdMarqueRoute: AppEspaceProjetsIdMarqueRoute,
    AppEspaceProjetsIdMediasRoute: AppEspaceProjetsIdMediasRoute,
    AppEspaceProjetsIdPartageRoute: AppEspaceProjetsIdPartageRoute,
    AppEspaceProjetsIdPlanRoute: AppEspaceProjetsIdPlanRoute,
    AppEspaceProjetsIdReglagesRoute: AppEspaceProjetsIdReglagesRoute,
    AppEspaceProjetsIdStatistiquesRoute: AppEspaceProjetsIdStatistiquesRoute,
    AppEspaceProjetsIdTypologiesRoute: AppEspaceProjetsIdTypologiesRoute,
    AppEspaceProjetsIdVisiteRoute: AppEspaceProjetsIdVisiteRoute,
    AppEspaceProjetsIdIndexRoute: AppEspaceProjetsIdIndexRoute,
  }

const AppEspaceProjetsIdRouteRouteWithChildren =
  AppEspaceProjetsIdRouteRoute._addFileChildren(
    AppEspaceProjetsIdRouteRouteChildren,
  )

interface AppEspaceRouteRouteChildren {
  AppEspaceOrganisationRoute: typeof AppEspaceOrganisationRoute
  AppEspaceIndexRoute: typeof AppEspaceIndexRoute
  AppEspaceProjetsIdRouteRoute: typeof AppEspaceProjetsIdRouteRouteWithChildren
}

const AppEspaceRouteRouteChildren: AppEspaceRouteRouteChildren = {
  AppEspaceOrganisationRoute: AppEspaceOrganisationRoute,
  AppEspaceIndexRoute: AppEspaceIndexRoute,
  AppEspaceProjetsIdRouteRoute: AppEspaceProjetsIdRouteRouteWithChildren,
}

const AppEspaceRouteRouteWithChildren = AppEspaceRouteRoute._addFileChildren(
  AppEspaceRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppEspaceRouteRoute: typeof AppEspaceRouteRouteWithChildren
  AppConfirmerRoute: typeof AppConfirmerRoute
  AppLoginRoute: typeof AppLoginRoute
  AppReinitialiserRoute: typeof AppReinitialiserRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppEspaceRouteRoute: AppEspaceRouteRouteWithChildren,
  AppConfirmerRoute: AppConfirmerRoute,
  AppLoginRoute: AppLoginRoute,
  AppReinitialiserRoute: AppReinitialiserRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface EmbedRouteRouteChildren {
  EmbedSlugRoute: typeof EmbedSlugRoute
  EmbedVisiteSlugRoute: typeof EmbedVisiteSlugRoute
}

const EmbedRouteRouteChildren: EmbedRouteRouteChildren = {
  EmbedSlugRoute: EmbedSlugRoute,
  EmbedVisiteSlugRoute: EmbedVisiteSlugRoute,
}

const EmbedRouteRouteWithChildren = EmbedRouteRoute._addFileChildren(
  EmbedRouteRouteChildren,
)

interface PSlugRouteChildren {
  PSlugDonneesPersonnellesRoute: typeof PSlugDonneesPersonnellesRoute
  PSlugLotNumeroRoute: typeof PSlugLotNumeroRoute
}

const PSlugRouteChildren: PSlugRouteChildren = {
  PSlugDonneesPersonnellesRoute: PSlugDonneesPersonnellesRoute,
  PSlugLotNumeroRoute: PSlugLotNumeroRoute,
}

const PSlugRouteWithChildren = PSlugRoute._addFileChildren(PSlugRouteChildren)

interface PRouteRouteChildren {
  PSlugRoute: typeof PSlugRouteWithChildren
}

const PRouteRouteChildren: PRouteRouteChildren = {
  PSlugRoute: PSlugRouteWithChildren,
}

const PRouteRouteWithChildren =
  PRouteRoute._addFileChildren(PRouteRouteChildren)

interface EnEmbedRouteRouteChildren {
  EnEmbedSlugRoute: typeof EnEmbedSlugRoute
  EnEmbedTourSlugRoute: typeof EnEmbedTourSlugRoute
}

const EnEmbedRouteRouteChildren: EnEmbedRouteRouteChildren = {
  EnEmbedSlugRoute: EnEmbedSlugRoute,
  EnEmbedTourSlugRoute: EnEmbedTourSlugRoute,
}

const EnEmbedRouteRouteWithChildren = EnEmbedRouteRoute._addFileChildren(
  EnEmbedRouteRouteChildren,
)

interface EnPSlugRouteChildren {
  EnPSlugPrivacyRoute: typeof EnPSlugPrivacyRoute
  EnPSlugLotNumeroRoute: typeof EnPSlugLotNumeroRoute
}

const EnPSlugRouteChildren: EnPSlugRouteChildren = {
  EnPSlugPrivacyRoute: EnPSlugPrivacyRoute,
  EnPSlugLotNumeroRoute: EnPSlugLotNumeroRoute,
}

const EnPSlugRouteWithChildren =
  EnPSlugRoute._addFileChildren(EnPSlugRouteChildren)

interface EnPRouteRouteChildren {
  EnPSlugRoute: typeof EnPSlugRouteWithChildren
}

const EnPRouteRouteChildren: EnPRouteRouteChildren = {
  EnPSlugRoute: EnPSlugRouteWithChildren,
}

const EnPRouteRouteWithChildren = EnPRouteRoute._addFileChildren(
  EnPRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRouteRoute: SiteRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  EmbedRouteRoute: EmbedRouteRouteWithChildren,
  PRouteRoute: PRouteRouteWithChildren,
  EnEmbedRouteRoute: EnEmbedRouteRouteWithChildren,
  EnPRouteRoute: EnPRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
